First edits LC-MS workflow
mzmine/mzmine_documentation pull request #11
Opened 2022-01-24 16:57 UTC by titodamiani

2022-01-24 18:09 UTC, SteffenHeu requested changes

2022-01-24 18:09 UTC, SteffenHeu commented on docs/workflows/lcmsworkflow/lcms-workflow.md
> +![workflow-image](https://github.com/titodamiani/mzmine_documentation/blob/e90deb3ccb11b18c94f7f27ed76f71c818640091/docs/workflows/lcmsworkflow/workflow-image.png)
use relative paths for images please. it would be jsut ![workflow-image](workflow-image.png) here i think

2022-01-24 18:09 UTC, SteffenHeu commented on docs/workflows/lcmsworkflow/lcms-workflow.md
> +The following workflow is intended to turn raw LC-MS data into a table of all the detected features and corrisponding signal intensity detected in each sample. A schematic representation of the workf
corr**e**sponding

2022-02-06 20:17 UTC, SteffenHeu commented
There seem to be some broken links, please fix them. You can check the "Check Markdown links / markdown-link-check (pull_request)" to view what's going on.

I recommend using an IDE, then the links will be updated automatically when moving files. I use IntelliJ for Java and Markdown. Maybe there are better IDEs for Markdown though.

2022-02-11 22:32 UTC, titodamiani commented
Uploaded the files in the correct folder. Now they work in the .md

2022-02-18 15:21 UTC, merged