Local minimum resolver and "How do I determine the instrumental noise level in my data?" section
mzmine/mzmine_documentation pull request #31
Opened 2022-04-16 16:01 UTC by titodamiani

2022-04-16 16:07 UTC, titodamiani commented
The https://code.google.com/p/mztab/wiki/jmzTab link in the wikiacknowledgements.md file is broken, but I haven't added it. Don't know where it comes from

2022-04-16 16:10 UTC, titodamiani commented
ERROR    -  Missing 1 link(s):
WARNING  -    | #module_docs/featdet_adap_chromatogram_builder/adap-chromatogram-builder/:min-group-size-in--of-scans

The link is actually correct, I think

2022-04-29 14:34 UTC, titodamiani commented
Hi guys, I completed the LMR doc with the last details. So whenever you want, you can double check and we can merge. Now Markdown links are fine, but I can't open the CI details to see what's going wrong.

2022-05-02 19:22 UTC, titodamiani commented
ERROR - Missing 1 link(s):
WARNING - | #module_docs/featdet_adap_chromatogram_builder/adap-chromatogram-builder/:min-group-size-in--of-scans

The link works. It just doesn't like the '#' character in the title of the subsection linked (i.e. Min group size in # of scans)

2022-05-05 08:24 UTC, SteffenHeu commented
Maybe we should replace that by "number" then and see if we can fix the issue that way.

2022-05-05 08:26 UTC, titodamiani commented
I already tried and it works. So that's the problem. Will change it later today. Will you also change the name of the parameter in MZmine to avoid weird characters? Or it will stay as it is?

2022-05-05 08:30 UTC, SteffenHeu commented
I think in MZmine itself we use the "#" to keep the parameter names short and the windows compact. We could change it, but i think everyone should be able to tell that it's the same parameter.

2022-05-05 16:17 UTC, titodamiani commented
I fixed the CI link. Now there is the https://code.google.com/p/jmzml in `./docs/wikiacknowledgements.md` that is failing. The link actually works and I didn't touch that MD document so I don't know what's the reason.

2022-05-06 14:08 UTC, SteffenHeu requested changes
only small typos

2022-05-06 14:08 UTC, SteffenHeu commented on docs/module_docs/featdet_resolver_local_minimum/local-minimum-resolver.md
> +During the EICs building, overalpping and partially co-eluting peaks are retained as single features in the faeture list (see, for example, [ADAP chromatogram builder](../featdet_adap_chromatogram_bu
faeture -> feature

2022-05-06 14:08 UTC, SteffenHeu commented on docs/module_docs/featdet_resolver_local_minimum/local-minimum-resolver.md
> +The algorithm examines all the data points in the EIC trace starting from the earliest RT. A scan window is set (see [Minimum search range RT/Mobility](#minimum-search-range-rtmobility-absolute) para
centred  -> centered

2022-05-06 14:08 UTC, SteffenHeu commented on docs/module_docs/featdet_resolver_local_minimum/local-minimum-resolver.md
> +4. Different vendors use different units of mobility. For instance, [TIMS](../../terminology/ion-mobility-terminology.md#trapped-ion-mobility-spectrometry-tims) express ions' mobility as Vs/cm<sup>2<
0.05 -> 1 for twims/dtims
twims dimension is something in the range of 10-30 ms
dtims is something in the range of 10-60 ms

2022-05-06 14:45 UTC, merged

2022-05-06 14:45 UTC, SteffenHeu commented
Cheers!